# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mark Danovich
email: mark.danovich@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal website and blog. Life, Science, Programming and Data Science.
twitter_username: mmasaniad
github_username: markd87
github_repo: markd87.github.io
google_analytics: UA-10819841-6

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true
# Set this to true to display tags on each post
show_tags: true

# Github and twitter are optional:
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/markd87/" }
    - { platform: twitter, user_url: "https://twitter.com/mmasaniad" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/markdanovich/",
      }

# Set this to true to get LaTeX math equation support
use_math: true

# Build settings
# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

collections:
  snippets:
    output: true
    permalink: /snippets/:path/

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
