name: Build notebooks
on: [push]

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: convert notebooks and word docs to posts
        uses: fastai/fastpages@master

      - name: Jekyll build
        uses: docker://jekyll/jekyll
        with:
          args: jekyll build --trace

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          publish_branch: master
          publish_dir: ./_site