name: Build notebooks
on: [push]

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: convert notebooks and word docs to posts
        uses: fastai/fastpages@master

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Run Jekyll
        uses: docker://faph/action-jekyll:1.5

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          # deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_dir: ./_site        